### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by tinaanit000** [bzaar/odict#30]
Hi, i happened to come to your brilliant site http://odict.ru/, and sadly found the file odict.csv.zip seem to be broken. I downloaded it but could't open it successfully. Would you please take a little time to check it if possible?

**Comment by bzaar** [comment]
Hi, sorry for the late reply. I've checked odict.csv.zip just now and it downloaded and opened fine. Please try again and if you can't get it to open, post the error message here. Thanks.
